# Generated by Django 5.1 on 2024-09-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipes',
            new_name='Recipe',
        ),
    ]
