# Generated by Django 5.1 on 2024-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_contact',
            field=models.IntegerField(max_length=15),
        ),
    ]
