# Generated by Django 5.1 on 2024-09-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0006_alter_student_student_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentID',
        ),
    ]
